linters:
  enbale:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - gosimple
    - deadcode
    - unused
    - ineffassign
    - structcheck
    - typecheck
    - stylescheck
    - misspell
    - revive
  disable:
    - funlen
    - gocyclo
    - depguard
    - dupl

run:
  timeout: 5m
  skip-dirs:
    - .git
    - .github
  skip-files:
    - ".*_test.go"

issues:
  max-issues-per-linter: 0
  max-same-issues: 5

output:
  sort-results: true
  format: colored-line-number


linters-settings:
  staticcheck:
    checks: ["all"]
  govet:
    check-shadowing: true
  revive:
    ignore-generated-header: true 
  misspell:
    locale: "UK"

gofmt:
  simplify: true

complexity:
  cyclo: 15
