name: CI

on:
  push:

jobs: 
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Run Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

  test:
    name: Unit Tests & Code Coverage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.21', '1.23']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./... -coverprofile=coverage.out 

      - name: Display Coverage
        run: go tool cover -func=coverage.out
    
  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - lint
      - test

    strategy:
      matrix:
        go-version: ['1.21', '1.23']

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build App
        run: go build -v ./...
