Name: CI

on:
  push:
    bracnhes: [ main ]
  pull_request:

jobs: 
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: [1.23]

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.54.2

      - name: Run Lint
        run: golangci-lint run

  test:
    name: Unit Tests & Code Coverage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.20.x', '1.21.x', '1.23.x']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./... -coverprofile=coverage.out 

      - name: Display Coverage
        run: go tool cover -func=coverage.out
    
  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - lint
      - test

    strategy:
      matrix:
        go-version: [ '1.20.x', '1.21.x', '1.23.x']

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build App
        run: go build -v ./...
